version: 2.0

defaults: &defaults
  docker:
    - image: circleci/android:api-28-alpha
  working_directory: ~/viewmodel-inject
  environment:
    _JAVA_OPTIONS: "-Xmx1400m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2"
    TERM: dumb

cache_key: &cache_key
  key: jars-{{ checksum "build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

update_sdk: &update_sdk
  name: Update SDK
  command: |
    mkdir "$ANDROID_HOME/licenses" || true
    echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
    echo "84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
    sdkmanager "platform-tools" "platforms;android-28"
download_dependencies: &download_dependencies
  name: Download Dependencies
  command: ./gradlew dependencies --no-daemon

report_artifacts: &report_artifacts
  path: reports
  destination: reports

jobs:
  test:
    <<: *defaults
    steps:
      - run:
          <<: *update_sdk

      - checkout

      - restore_cache:
          <<: *cache_key

      - run:
          <<: *download_dependencies

      - run:
          name: Install Updated Runtime JAR
          command: ./gradlew viewmodel-inject-runtime:installJar

      - run:
          name: Run Tests
          command: ./gradlew viewmodel-inject-processor:test viewmodel-inject-runtime:testDebugUnitTest viewmodel-inject-runtime-ktx:testDebugUnitTest --no-daemon

      - run:
          name: Copy Test Results
          command: |
            mkdir -p ./test-results/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ./test-results/ \;

      - save_cache:
          <<: *cache_key
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper

      - store_artifacts:
          <<: *report_artifacts

      - store_test_results:
          path: test-results/

  publish:
    <<: *defaults
    steps:
      - run:
          <<: *update_sdk

      - checkout

      - restore_cache:
          <<: *cache_key

      - run:
          <<: *download_dependencies

      - run:
          name: Install Updated Runtime JAR
          command: ./gradlew viewmodel-inject-runtime:installJar

      - run:
          name: Publish Processor
          command: ./gradlew clean build viewmodel-inject-processor:bintrayUpload -PbintrayUser=$BINTRAY_USER -PbintrayKey=$BINTRAY_KEY -PdryRun=false

      - run:
          name: Publish Runtime
          command: ./gradlew clean build viewmodel-inject-runtime:bintrayUpload -PbintrayUser=$BINTRAY_USER -PbintrayKey=$BINTRAY_KEY -PdryRun=false

      - run:
          name: Publish Kotlin Extensions
          command: ./gradlew clean build viewmodel-inject-runtime-ktx:bintrayUpload -PbintrayUser=$BINTRAY_USER -PbintrayKey=$BINTRAY_KEY -PdryRun=false

      - save_cache:
          <<: *cache_key
          paths:
          - ~/.gradle/caches
          - ~/.gradle/wrapper

workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
          - test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
